version: "3.5"

volumes:
  elasticsearch-data: ~

services:
  app:
    image: ${APP_NAME}/app-dev
    build:
      context: ./docker
    volumes:
      - ./:/usr/src/app
    links:
      - es

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    container_name: ${APP_NAME}-dev-es
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - ${ELASTICSEARCH_HOST_PORT}:9200
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true