PUT http://localhost:29200/faces
Content-Type: application/json


{
  "mappings" : {
      "properties" : {
        "face_name" : {
          "type" : "keyword"
        },
        "face_encoding" : {
          "type" : "dense_vector",
          "dims" : 128
        }
      }
    }
}

